### ISSUE TITLE
IDLE on two IMAP accounts

### ISSUE THREAD

**Issue by JackalWorks** [lefcha/imapfilter#101]
I am running imapfilter in a loop, which are waiting for the IDLE to return. However I have two accounts, and I want the filters to run when any of the the INBOXes exits from IDLE. I tried to run each account in a coroutine, but it doesn't work. And just having the IDLE in a coroutine only causes several issues (I guess due to the account being in idle while trying to perform the commands).

**Comment by lefcha** [comment]
The simplest solution to this problem would be to run two imapfilter instances with different configuration files using the `-c` option.  It might cause some duplication of some parts, but you could overcome this issue by having some common `.lua` file, which you would then include from your separate config files.

Using coroutines is complicating things, and actually I don't think that it can work, because coroutines assume that calls are non-blocking, while the IDLE mode is a blocking call that is expecting for some network packets to be received.  Also, Lua doesn't have the control at that point (in IDLE mode), it's a C function in wait that has the control...

**Comment by JackalWorks** [comment]
Yes, the simple solution seem to be the one I will go for, I think it will work satisfactorily.
