### ISSUE TITLE
Connection fails to Gmail using Oauth2

### ISSUE THREAD

**Issue by mat-mathews** [lefcha/imapfilter#115]
When trying to use the Oauth2 connection options, attempting to use tls1.2 or ssl3 the connection times out

imapfilter: timeout period expired while waiting to read data
imapfilter: login request to xxxxxx@gmail.com@imap.gmail.com failed
	[C]: in function 'error'
	/usr/local/share/imapfilter/account.lua:81: in function '_check_result'
	/usr/local/share/imapfilter/account.lua:97: in function '_login_user'
	/usr/local/share/imapfilter/account.lua:59: in function 'IMAP'

**Comment by lefcha** [comment]
I tried to reproduce this, and it seems that this happens when the OAuth2 string is incorrect, as when I use the correct string everything works fine for me. For some reason the server doesn't respond with a failure but it just doesn't send a reply back, and then imapfilter times out because of the inactivity.

You could try increasing the `options.timeout` as its default value is `60` seconds, but I don't think that's your problem, as to me it seems that your OAuth2 string is incorrect.

**Comment by mat-mathews** [comment]
After updating openssl and rebuilding, this is no longer an issue. However, I'm  90% convinced that you were correct my OAuth2 string just wasn't correct.

thanks so much
