### ISSUE TITLE
Outlook rules

### ISSUE THREAD

**Issue by ryanknutson** [lefcha/imapfilter#118]
I have my email filters setup in Outlook and would like to move them to use Imapfilter. Is it possible to export a rules file and use that? Thanks.

**Comment by lefcha** [comment]
Unfortunately, imapfilter doesn't have any import functionality for other filtering software, so you can't just export the rules and use them, but you would need to rewrite them using imapfilter's syntax.

**Comment by Papafox** [comment]
One possible solution would be to export the Outlook rules as text and then
use an edit macro to convert the rules to lua.

There is a utility on Github
<https://github.com/dlisikov/outlook-gmail-rules-export> which will export
Outlook mail rules as text, xml or csv.  You could use it (or since it's a
C# program, modify the source) to export the rules and generate imapfilter
lua rules.







————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org

**Comment by ryanknutson** [comment]
Thank you! Will try.
