### ISSUE TITLE
always tries to connect through SSL but fails

### ISSUE THREAD

**Issue by marcelser** [lefcha/imapfilter#123]
Hello,

I have a server which is reachable on port 993 (ssl) and port 143 (normal imap)

On Port 993 it uses a self signed certificate which obviously imapfilter doesn't like. It always reports
imapfilter: initiating SSL connection to imap.shadowsrealm.ch; error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small
imapfilter: login request to marc@imap.shadowsrealm.ch failed
stack traceback:
        [C]: in function 'error'
        /usr/share/imapfilter/account.lua:68: in function '_check_result'
        /usr/share/imapfilter/account.lua:84: in function '_login_user'
        /usr/share/imapfilter/account.lua:46: in function 'IMAP'
        /root/.imapfilter/config.lua:31: in main chunk

But no matter what I do in configuration I can not make imapfilter NOT use ssl. Even if I remove the 'ssl' key and set port to '143' it still outputs the above error.

There should definitly be a method to disable ssl if needed to overcome the above error. And there should probably be something like --insecure to use self signed certs

**Comment by Papafox** [comment]
There are three different problems here:
1. SSL handshake failure
2. Howto disable SSL
3. Howto use a self-signed certificate with Imapfilter

**SSL Handshake Failure**

> imapfilter: initiating SSL connection to imap.shadowsrealm.ch; error:14082174:SSL routines:ssl3_check_cert_and_algorithm:dh key too small

The key info here is "ssl3_check_cert_and_algorithm:dh key too small".  This is a new feature introduced by the latest version of OpenSSL.  It throws this error when it finds a DH key of less than 768 bits.  (DH = Diffie-Hellman key, which is used during the key-exchange handshake) Note that this is not a certificate error, and is outside the control of Imapfilter. My guess is that it is caused by a server configuration error.

**Howto Disable SSL**

In Imapfilter, the "ssl=" option of the account macro will cause the SSL protocol to be used.  To avoid SSL, either delete or comment out the SSL= line

**Howto Use a Self-Signed Certificate with Imapfilter**

Normally, Imapfilter will verify a certificate using the truststore (usually a directory '/etc/ssl/certs').  Imapfilter uses the OpenSSL verify routines which walk the certificate issuer chains, checking the intermediate and root certificates against copies in the truststore.  This won't work with self-signed certificates.

To use a self-signed certificate run Imapfilter at the command line - that is with stdin/stdout connected to a terminal:

`imapfilter -v -c shadowsrealm.test`

You will see something like this:

```
Server certificate subject: /C=CH/ST=ZH/L=Zuerich/O=Courier Mail Server/OU=Automatically-generated IMAP SSL key/CN=imap.shadowsrealm.ch/emailAddress=marc@shadowsrealm.ch
Server certificate issuer: /C=CH/ST=ZH/L=Zuerich/O=Courier Mail Server/OU=Automatically-generated IMAP SSL key/CN=imap.shadowsrealm.ch/emailAddress=marc@shadowsrealm.ch
Server certificate serial: 8A5CD85E58AB9A8A
Server key fingerprint: 7A:E1:7E:DE:B6:27:FD:A7:7C:91:16:A2:1D:35:DB:FA
(R)eject, accept (t)emporarily or accept (p)ermanently?
```
Reply 'P" and Imapfilter will store a copy of the cert in the `~/.imapfilter/certificates` file. Once there, Imapfilter can be run normally and it will accept the self-sugned certificate as valid.

**Comment by marcelser** [comment]
Hi Matthew,

Thank you very much for your explanations. But point 2 is not correct.
Removing the "ssl=" line from the configuration was the first thing I 
tried after reading the imapfilter documentation. No matter if the line 
exists or not, imapfilter still throws the SSL Handshake error. Maybe 
it's caused by the other 2 mail accounts I have configured that use SSL. 
Maybe then imapfilter incorrectly uses ssl also for the 3rd mail account 
although there is no "ssl=" line. I could try removing the other 2 mail 
accounts if you wish to check if that's the problem.

Best regards,

Marc

**Comment by lefcha** [comment]
If imapfitler still tries to setup an encrypted connection when you don't specify the `ssl` account variable and you connect to port 143, then it might be the IMAP STARTTLS extension.  If the server supports it, imapfilter tries to negotiate again an SSL/TLS connection, and this is the default behavior.  You can disable this with `options.starttls = false`.  Can you also try this?

**Comment by marcelser** [comment]
Hi,

setting options.starttls=false omitting 'tls=' did the trick. Thank you 
for your help.

Best regards,

Marc

Am 20.03.2016 um 21:24 schrieb Lefteris Chatzimparmpas:

**Comment by graemev** [comment]
I've read lots of different "solutions" to using self-signed certs in imapfilter.

1. Using imapfilter -c imaptest1.lua -d debug -t $PWD/truststore
2: Adding the cert into ~/.imapfilter/certificates
3: I used openssl s_client -connect imap.home:993 -status -verifyCApath $PWD/truststore
   (it reported     Verify return code: 0 (ok) )

So based on the above:
   imapfilter -v -c shadowsrealm.test

I used:  (after deleting everything in ~/.imapfilter/certificates )

$ imapfilter -v -c imaptest1.lua 
S (3): * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot (Debian) ready.
C (3): 1000 CAPABILITY
S (3): 1000 OK Pre-login capabilities listed, post-login capabilities have more.
C (3): 1001 STARTTLS
S (3): 1001 OK Begin TLS negotiation now.
imapfilter: initiating SSL connection to imap.home; error:0A000086:SSL routines::certificate verify failed

So I did not get the prompt suggested .
