### ISSUE TITLE
2.6.7 fails to build on El Capitan

### ISSUE THREAD

**Issue by fm2802** [lefcha/imapfilter#128]
$ make
...
cc -o imapfilter   auth.o buffer.o cert.o core.o file.o imapfilter.o list.o log.o lua.o memory.o misc.o namespace.o pcre.o regexp.o request.o response.o session.o signal.o socket.o system.o -lm -ldl -llua -lpcre -lssl -lcrypto 
Undefined symbols for architecture x86_64:
  "_TLSv1_1_client_method", referenced from:
      _main in imapfilter.o
  "_TLSv1_2_client_method", referenced from:
      _main in imapfilter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [imapfilter] Error 1
make: *** [all] Error 2

$ openssl version
OpenSSL 1.0.2h  3 May 2016

**Comment by lefcha** [comment]
This sounds like an OS problem and how/where the OpenSSL is installed, and unfortunately I can't help you much since I don't have access or knowledge of this OS.

I think you should try to search on the web for info on that problem and specifically for the `Undefined symbols for architecture x86_64: "_TLSv1_1_client_method", referenced from:` message...

Or maybe someone else that knows more about this can help you...

**Comment by Papafox** [comment]
I don't have an OSX system to test on, but imapfilter with openSSL 1.0.2h
builds correctly with Linux and FreeBSD.

I agree with Lefteris - it sounds like a build config issue, probably it's
not finding the libssl.so library in the search path.  An alternative is
that your version of openssl was built without TLSv1.1 and TLSv1.2 support






————————————————————————————————————————————————————
*Matthew Donald*
m: +61-(0)431 607 492
e:  matthew@wsadmin.org
