### ISSUE TITLE
gmail account login

### ISSUE THREAD

**Issue by hidroto** [lefcha/imapfilter#135]
I get this error

> Enter password for ____@imap.gmail.com: 
> imapfilter: login request to ____@imap.gmail.com failed
> stack traceback:
>        [C]: in ?
>        [C]: in function 'error'
>        /usr/local/share/imapfilter/account.lua:81: in field '_check_result'
>        /usr/local/share/imapfilter/account.lua:97: in field '_login_user'
>        /usr/local/share/imapfilter/account.lua:59: in global 'IMAP'
>        /home/Adamas/.imapfilter/config.lua:3: in main chunk

and am using this config

> options.timeout = 120
> -- imapfilter for gmail
> google_account = IMAP {
>     server = 'imap.gmail.com',
>     username = '____',
>     port = 993,
> }
> 
> -- Get a list of the available mailboxes and folders
> mailboxes, folders = google_account:list_all()
> 
> google_account.INBOX:check_status()
> print("hello\n")

have i mess configuerd the config.lua file?

**Comment by arunpersaud** [comment]
Hi

not sure, I'm using the following which works for me

GMAIL = IMAP {
    server = 'imap.gmail.com',
    username = 'xxx@yyy.zzz',
    password = '_____',
    ssl = 'tsl1',
}

**Comment by lefcha** [comment]
Unless the problem is that you didn't give the correct username format or the correct `ssl` option, as mentioned before, one other problem might be that you need to enable support for so called `Less secure apps` in Gmail.

You might be able to see more details of the exact problem if you run imapfilter with `-v` or `-d debug.log`, and investigate the messages in the terminal or the `debug.log` file.  You should be looking for a more detailed server response.

If you don't want to do that, imapfilter has support for Google's OAuth2 authentication (I'm actually using that myself in one of my accounts), and you can find more details about that in the [samples/extend.lua](https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua#L124-L161) file.

**Comment by hidroto** [comment]
@lefcha when i run imapfilter -v -d imap.log i get the same results and nothing is written to the imap.log file. i even tried supplying my password in the config file.

**Comment by lefcha** [comment]
Are you using the email address as username, including the `@gmail.com` part, or whatever your domain is?

Also, did you check your Google/Gmail settings, whether `Less secure apps` are allowed to connect to the Gmail server?
