### ISSUE TITLE
imapfilter on runbox server

### ISSUE THREAD

**Issue by unrulybeep** [lefcha/imapfilter#152]
hello,

I have used imapfilter in the past for icloud and polarismail (emailarray.com), and it was successful. I have moved servers since and it's been awhile since I've used the program. Thanks for it btw, has been very useful so far. Unfortunately now I am facing a problem and I'm not sure why. I can login to the account, but none of my searches respond.

This is the response I get after running the imapfilter command.
>[1] user@server> imapfilter -v -d imapfdebug -c .imapfilter/accounts.lua                                                                                                                                         
> S (4): * OK IMAP4 ready
> C (4): 1000 NOOP
> S (4): 1000 OK completed
> C (4): 1001 CAPABILITY
> S (4): 1001 OK completed
> C (4): 1002 LOGIN "username%domain" *
> S (4): 1002 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in
> C (4): 1003 CAPABILITY
> S (4): 1003 OK Capability completed.
> C (4): 1004 NAMESPACE
> S (4): 1004 OK Namespace completed.
> C (4): 1005 LOGOUT
> S (4): 1005 OK Logout completed.

I have also tried using interactive mode but, again, I can get a response with check_status() but nothing else. check_status() pulls:

> account1.INBOX:check_status()
C (4): 1005 STATUS "INBOX" (MESSAGES RECENT UNSEEN UIDNEXT)
S (4): 1005 OK Status completed.
370 messages, 0 recent, 76 unseen, in username%domain@mail.runbox.com/INBOX.

then when I try anything else, nothing is retrieved:
> account1.INBOX:is_new()
C (4): 1006 SELECT "INBOX"
S (4): 1006 OK [READ-WRITE] Select completed (0.030 secs).
C (4): 1007 UID SEARCH ALL NEW
S (4): 1007 OK Search completed (0.000 secs).
> account1.INBOX:is_unseen()
C (4): 1008 UID SEARCH ALL UNSEEN
S (4): 1008 OK Search completed (0.000 secs).

I know I must be doing something wrong, but I'm uncertain of what it is. Or perhaps my new email host (runbox) is not compatible with imapfilter somehow? Is there any guidance you have to give? thx

**Comment by lefcha** [comment]
The status in this case reports `76 unseen` but `0 recent` so `is_new()` should return no messages (this is because it only returns both unseen and recent messages).  But the `is_unseen()` should return `76 unseen` messages...

First, make sure you run imapfilter with `-d debug.log` and have a look at the `debug.log` file it wrote, as that contains the exact details on what the server responded, ie. which messages were returned.  Then, also try calling just `select_all()`, as it should return all message in the mailbox.

If the server is compliant with the IMAP specification (RFC 3501) it should not behave like that, and the IMAP spec is the common ground on how the server and the client (ie. imapfilter) should talk with one another.

If the server doesn't return anything even with `select_all()` and you know there are messages in that mailbox, then I suggest you try to investigate why the server doesn't allow `SEARCH queries` in the server's FAQ or asking the admins, else your only other bet is to workaround this by using the imapfilter's `match_*()` methods...

**Comment by unrulybeep** [comment]
Thank you for the help. I'm not entirely sure what I am doing different today but it is working.
