### ISSUE TITLE
certificate verification failed

### ISSUE THREAD

**Issue by ovitus** [lefcha/imapfilter#192]
My config.lua config:

local account = IMAP {
        server = 'mailhost.domain.net',
        username = 'john.doe',
        password = 'mypassword',
        ssl = 'ssl3',
}

but I get the following error message:

[jdoe@host .imapfilter]$ imapfilter
imapfilter: certificate verification failed; 19
imapfilter: login request to john.doe@mailhost.domain.net failed
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        /usr/share/imapfilter/account.lua:81: in field '_check_result'
        /usr/share/imapfilter/account.lua:97: in field '_login_user'
        /usr/share/imapfilter/account.lua:59: in global 'IMAP'
        /home/jdoe/.imapfilter/config.lua:1: in main chunk

**Comment by Papafox** [comment]
The significant part of

> imapfilter: certificate verification failed; 19

 is the error code 19 which is X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN.  You
can find the error codes listed in x509_vfy.h . This error means that the
certificate chain is broken. While the root certificate in the certificate
chain is always self-signed, all the others should be signed by the
previous cert in the chain.

To debug this problem, use openssl to connect to your IMap server, as
follows:

openssl s_client -connect mailhost.domain.net:993 -status -verifyCApath
/etc/ssl/


The results are:

CONNECTED(00000003)
depth=0 C = US, ST = CA, L = SF, O = DomainNET, OU = IMAP server, CN =
nuhost.domain.net, emailAddress = hostmaster@domain.net
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = CA, L = SF, O = DomainNET, OU = IMAP server, CN =
nuhost.domain.net, emailAddress = hostmaster@domain.net
verify return:1
OCSP response: no response sent
---
Certificate chain
 0 s:C = US, ST = CA, L = SF, O = DomainNET, OU = IMAP server, CN =
nuhost.domain.net, emailAddress = hostmaster@domain.net
   i:C = US, ST = CA, L = SF, O = DomainNET, OU = IMAP server, CN =
nuhost.domain.net, emailAddress = hostmaster@domain.net
---

The first thing that strikes me is that error is now 18 (self-signed
certificate), rather than 19 (self-signed certificate in chain).  On this
test, a single certificate is on use, rather than a chain of certificates.
If you wish to use a self-signed certificate, you need to place a copy in
your truststore (normally /etc/ssl/)

The second issue is that the certificate returned is for 'nuhost.domain.net'
rather than 'mailhost.domain.net'.  Even if you self-signed cert is
accepted, you would get an error 62 (host name mismatch).  Make sure that
either the CN rdn or an altname matches the domain name specified in the
IMAP{} entry.

Matthew
