### ISSUE TITLE
Grep Like search with variables?

### ISSUE THREAD

**Issue by WernerAUT** [lefcha/imapfilter#206]
Hello,

sorry to post in issues and please feel free to close/delete it, but i have a question if this is possible with imapfilter.

I want to look in "test1" folder and take from the mail the contain_to and use that as variable,
so something like that?
toadress = account["test1"]:contain_to()

and then i want to look in test2 folder and search inside the messages if it has the "toadress" inside
messages = account["test2"]:contain_message(toadress)

then i want to move the messages found into test3 folder
messages:move_messages(account["test3"])

and also move the matched emails from test1 folder to test3 folder, their i have the first issue, how could i do that, and as i tested this way i know that doesn't work, but i hope it makes sense to understand what i want.

TIA

**Comment by lefcha** [comment]
So you want to somehow get a list of all unique 'To' header fields? That's not what `contain_to()` does, as that one expects an argument, the `To` address you're searching, and returns the messages matching.

In theory you could get a list of all messages in a folder with `select_all()` and then fetch the `To` field of each message with `fetch_field('to')`.  But if you have hundreds or thousands of messages, that will take some time and some downloading to complete, and then some searching in the second folder.  But it should be doable.

The general structure of such script would look like some of the examples in the https://github.com/lefcha/imapfilter/blob/master/samples/extend.lua file, for example: https://github.com/lefcha/imapfilter/blob/cc5a6480586f514b4faffe26c16a93f9569f2f68/samples/extend.lua#L46-L57

The difference in your case would be that instead of `fetch_message()` you do the much faster `fetch_field('to')`, and instead of checking the message with `pipe_to()` you would instead use the `To` field of the message to do another search with `contain_message()`, and immediately move the the matching messages to the third folder, instead of putting the results in an array and acting at the end.

**Comment by WernerAUT** [comment]
thanks for your answer but thats to much for me for the basic skills i have. So maybe i need to search someone with programming skills :)

**Comment by lefcha** [comment]
This might work:

```lua
all = account['test1']:select_all() 
 
toaddresses = {} 
for _, mesg in ipairs(all) do 
    mbox, uid = table.unpack(mesg) 
    field = mbox[uid]:fetch_field('to') 
    toaddresses[field] = true
end 
 
messages = Set {} 
for toaddress, _ in pairs(toaddresses) do
    messages = messages + account['test2']:contain_message(toaddress:sub(5))
end

messages:move_messages(account['test3'])
```

I would give that a try with `copy_messages()` to a new/empty mailbox (instead of `move_messages()`), just to observe how it worked, and if it copied all messages expected.

**Comment by WernerAUT** [comment]
awesome that copies the mail in test 2 to test3
but i need also a way to copy the mail from test1 to test3

test1 = to field is test@mail.com
test2 = message has inside the mailtext test@mail.com
test3 = both mails are getting moved into it

mail in test1 and mail in test2 which are a match are getting moved into test3

thanks for the help!

**Comment by lefcha** [comment]
This scripts gathers all `To` addresses of all messages in `test1`, then searches for those `To` addresses in `test2`, and finally moves the matching messages inside `test2` to `test3`.

All messages inside `test1` are already matching (remember we gather all possible `To` addresses from all messages), so you could also just the following at the end of the above script:

```lua
all:move_messages(account['test3'])
```

If you just need to search for specific `To` addresses like `test@maill.com`, then the script's first part is not needed.  You only need something like:

```lua 
toaddresses = { 'test@mail.com', 'test2@mail.com' }

messages = Set {} 
for _, toaddress in ipairs(toaddresses) do
    messages = messages + account['test1']:contain_message(toaddress)
    messages = messages + account['test2']:contain_message(toaddress)
end

messages:move_messages(account['test3'])
```

**Comment by WernerAUT** [comment]
oh awesome i was thinking all:move_messages(account['test3']) moves really all messages inside test1 to test3 but i tested it now and it only moved the matched ones, thats amazing wow, thats exactly what i need, many thanks for your help and also thanks for imapfilter, this tool makes it so much easier!!

**Comment by lefcha** [comment]
> oh awesome i was thinking all:move_messages(account['test3']) moves really all messages inside test1 to test3 but i tested it now and it only moved the matched ones, thats amazing wow, thats exactly what i need, many thanks for your help and also thanks for imapfilter, this tool makes it so much easier!!

If you do:

```lua
all = account['test1']:select_all() 
all:move_messages(account['test3'])
```

Then you basically move all messages from `test1` to `test3`, as `select_all()` matches all messages in the mailbox.

Just making sure you understand this, and you don't run into unexpected results.

**Comment by WernerAUT** [comment]
yes i know i have it at the end of the script and i tested it the ones which doesn't match stay in test1

`all = account['test1']:select_all() 
 
toaddresses = {} 
for _, mesg in ipairs(all) do 
    mbox, uid = table.unpack(mesg) 
    field = mbox[uid]:fetch_field('to') 
    toaddresses[field] = true
end 
 
messages = Set {} 
for toaddress, _ in pairs(toaddresses) do
    messages = messages + account['test2']:contain_message(toaddress:sub(5))
end

messages:move_messages(account['test3'])
all:move_messages(account['test3'])`
