### ISSUE TITLE
Feature request: force reload of configuration file with kill -HUP signal

### ISSUE THREAD

**Issue by internationils** [lefcha/imapfilter#208]
Hello,
I have imapfilter running in an enter_idle() loop, and need to restart it occasionally to reload its configuration after adding rules. It would be great if it would be possible to trigger imapfilter to reload its configuration using a kill -HUP signal so I don't have to hard-kill it every time and restart it.

[Additional minor niggle: would be nice to have long options as well, like imapfilter --version]

**Comment by lefcha** [comment]
> Hello,
> I have imapfilter running in an enter_idle() loop, and need to restart it occasionally to reload its configuration after adding rules. It would be great if it would be possible to trigger imapfilter to reload its configuration using a kill -HUP signal so I don't have to hard-kill it every time and restart it.
> 
> [Additional minor niggle: would be nice to have long options as well, like imapfilter --version]

Hello!

It's possible to interrupt `enter_idle()` with the `SIGUSR1/SIGUSR2` signals, but it' currently not possible to `kill -HUP` the Lua interpreter which has control of executing the config, and thus somehow restart the whole process of reloading/executing the config.

There's a simpler workaround to reload your config though, described some time ago: https://github.com/lefcha/imapfilter/issues/73#issuecomment-60685208

Not sure if that suits you...

> [Additional minor niggle: would be nice to have long options as well, like imapfilter --version]

I can see how it's easier to remember a word than a single letter, but when I wrote imapfilter I was striving for POSIX compatibility of the source code (I think the code should still be POSIX compatible), and `getopt_long()` was (is still?) a GNU extension.  Also, I used BSD at the time, and short options is the standard there...

**Comment by internationils** [comment]
OK, thanks for the response, I can live with that.
When sending SIGUSR1/2 is the config reloaded or not? If not I will live with killing & restarting, or with the solution that you linked.
Feel free to close this issue. Thanks!

**Comment by lefcha** [comment]
The user signals are just interrupting the `enter_idle()`, which is basically waiting for network input from the IMAP server.  Thus then the line after the `enter_idle()` is executing in the config.  This is described in the `imapfiter_config(5)` man page:

> Apart from an event received by the server, the SIGUSR1 or SIGUSR2 signals can also interrupt the IDLE mode at any time, and the execution of the configuration file will then continue from the next line after the `enter_idle()`.  In this case only the value `true` is returned.

So the config is not reloaded in whole, and the idea is that you can interrupt the `enter_idle()` and then handle yourself how to proceed from there,  and you could also reload the config (if it was modified) the way I described above in the older post.

Since when `enter_idle()` is interrupted with the signal, it only returns `true` without a second value, you can then check forf this, skip all further processing, and go directly to the end of your config.  If you then have the solution I gave above, it would basically mean that you reload your config.

But the difference with `SIGHUP` is that you handle gracefully the reload, instead of imapfilter stopping abruptly the Lua interpreter, possibly doing some cleanup of IMAP sessions, data structures, etc, and then restarting a new interpreter.

**Comment by lefcha** [comment]
I gave some thought into it, and it's basically impossible to handle a `SIGHUP` to reload the configuration file properly.  The reason is that the way imapfilter is implemented, it gives full control to the user through the configuration file.  So basically imapfilter gets control back when the configuration has been processed, which happens when the Lua interpreter function returns, and thus it's not possible to somehow get the signal and stop the Lua interpreter in a nice or sane way.

So the workaround I suggested is the only way to do this, since the user is responsible for what is happening through the configuration file; they have complete freedom of action, but this comes also with responsibility to handle these situations.

Some useful functionality would be to have a helper function available, that you could call and figure out if the process received a `SIGHUP` or even a `SIGTERM`.  The user then could call these functions and see if a signal was received, and then act accordingly (eg. reload config, cleanup and terminate gracefully, etc.).

But still the user would need to have 2 files, a kind of wrapper/static file and the main/dynamic/modifiable config file, and then use `dofile()` in order to execute the config file.  The only difference would be that instead of checking the modification time with `stat`, receiving `SIGHUP would be the trigger to reload on the next run of the loop.

**Comment by internationils** [comment]
Thanks ... could you perhaps provide a template / example of the two files with comments to show a best practice, or would you suggest just using the one in https://github.com/lefcha/imapfilter/issues/73#issuecomment-60685208 ?

**Comment by lefcha** [comment]
Until I implement a signal notification mechanism available in Lua for the users config, it's not possible to do what I described above.

For now you can use a simpler mechanism using for example `stat` or some other mechanism to decide when to reload the dynamic config file.

So you need to try something like the example in https://github.com/lefcha/imapfilter/issues/73#issuecomment-60685208.
