### ISSUE TITLE
Difference between * and meta-searching

### ISSUE THREAD

**Issue by sebastianludwig** [lefcha/imapfilter#220]
The manpage under **SEARCHING** reads

> The logical “and” is implemented using the ‘∗’ operator:
> ```
> results = myaccount.mymailbox:is_unseen() ∗
>        myaccount.mymailbox:is_larger(100000)
> ```

and further down under **META-SEARCHING**

> The results of the searching methods can be searched further on in the same way as searching is done in mailboxes. The difference is that instead of doing the search in the whole mailbox, ie. in all the messages, it is instead done only to those messages that were returned in a previous search.
> Examples:
> ```
> results:match_message(’ˆ[Hh]ello world!?$’)
> myaccount.mymailbox:is_new():match_body(’ˆ[Ww]orld, hello!?$’)
> ```

As long as the same mailbox is used, is there a difference between the following two rules?

```
account.mailbox:is_unseen() ∗ accounmymailbox:is_larger(100)
account.mailbox:is_unseen():is_larger(100)
```

I would expect the results to be identical but the first one to perform _two_ server-side searches and only _one_ for the second one, narrowing down the result set locally. Is that the case?

**Comment by lefcha** [comment]
There is a difference, but not exactly the one you mention, as both examples will do 2 server requests.

When doing searches with logical operators, independent searches take place to all of the messages of the mailbox, and then the results are combined locally, based on the operators used.

With meta-searching, the 1st search takes place on all the messages, but the 2nd search only happens on the messages that already matched the 1st search, the 3rd only on the messaged matched by the 2nd, etc.

So if  you have 100 messages, with combined searching, imapfilter does 2 queries on those 100 messages.  Let's say the 1st query yields 10 messages, and the 2nd yield 50 messages.  In the end you get only 7 messages that are both unseen and larger from that size.

With meta-searching, the 1st query yields 10 messages, and the 2nd query takes place only on those 10 messages, and in the end you get again 7 messages.  But the server only searched those 10 messages, and imapfilter also got back less results.

So in theory, it's faster to do meta-searching, because the server queries less data on meta-searches, and the client downloads less data, too.  If you want to do multiple queries on the same filtered messages, like only on the unseen messages, it's better if you get all the unseen messages, and then meta-search on them different ways:

```lua
unseen = account.mailbox:is_unseen()
large = unseen:is_larger(100)
old = unseen:is_older(7)
```

**Comment by sebastianludwig** [comment]
Sweet, thanks for the explanation!

Please excuse my lack of knowledge on how IMAP actually works 😬 Does the client have to send the message UIDs or something for meta-searches? Or can the client reference the result sets of previous searches?

Assuming I have a mailbox of 10000 unseen messages, all older than 7 days. So `:is_unseen()` and `:is_older(7)` would each return all 10k messages, also having to search through 10k messages no matter if `m:is_unseen() * m:is_older(7)` or `m:is_unseen:is_older(7)` is used. Would the latter variation be slower over all because the client needs to transmit the search set back to the server?

**Comment by lefcha** [comment]
The way this works is that the IMAP `SEARCH` command, has the option to either search all messages or the specified set of messages by UID.  Note that this set is not necessarily one-by-one, but for example it can be something like `123:134,234, 345:356`, etc. So consecutive UIDs are converted to a range of UIDs, and in most scenarios this should result in a shorter string to send.

If the 1st query yields 10k messages, then the search is not very well optimized.  It's recommended to order the queries such as the 1st one returns as few messages as possible, to optimize the meta-searching.

Now in the case where 2 queries return thousands of messages, it's probably better to not use meta-searching, unless the messages are quite consecutive, and they could possibly be a big range of UIDs.  It's probably not going to help the server to search in 10k messages.

Of course you can experiment and see.

**Comment by sebastianludwig** [comment]
Thank you very much, this helps a lot :-)
