### ISSUE TITLE
allow callback from C code to lua to refresh OAuth2 token

### ISSUE THREAD

**Issue by rhaas80** [lefcha/imapfilter#255]
OAuth2 tokens expire after a while and need to be refreshed using the refresh token.

This means that if one uses `options.recover = true` and imapfilter tries to recover due to an authentication failure it should try and use a refreshed token rather than the one copied during the initial login.

Right now there is no way for C to call back to Lua. I would like to propose (and am willing to code up an example) of a lua callback functionality that would eg add an option

```lua
Account.oauth2_refresh = fucntion() return new_token end
```

that lets one register a callback function that returns the new token to the C code.  
  
Mostly following the ideas outlined in [https://www.appsloveworld.com/c/100/12/store-a-lua-function](https://www.appsloveworld.com/c/100/12/store-a-lua-function) and the "Calling Lua functions from C/C++" section in [https://www.cs.usfca.edu/~galles/cs420/lecture/LuaLectures/LuaAndC.html](https://www.cs.usfca.edu/~galles/cs420/lecture/LuaLectures/LuaAndC.html)  
  
Would this be something that would stand a chance of inclusion? It changes imapfilters data flow a bit since it no longer is strictly from Lua to the C of imapfilter.

**Comment by lefcha** [comment]
Since https://github.com/lefcha/imapfilter/commit/f48fb06adc23315d1e437f5416cf7acde59b7779 the `oauth2` string is not stored on C, just the Lua config, and is supplied to C during login.

This means that it should be possible to replace the string `<account>.oauth2` whenever it needs replacing, and it should be picked up on the next login, or if you force a re-login.

Would that work?

**Comment by douglas-larocca** [comment]
Yes that works, thanks!
