### ISSUE TITLE
Allow the match_* functions on Mailbox to do case insensitive searches

### ISSUE THREAD

**Issue by slbmeh** [lefcha/imapfilter#87]
I see the `cflags` and `eflags` params for `regex_search`, but it isn't clear what they do. It looks like regexp.c always sets the `REG_ICASE` flag, but it doesn't appear to be working that way.

**Comment by lefcha** [comment]
It is a bit confusing, but imapfilter uses 2 different regular expressions libraries, in different places and in different ways:

1. It uses the POSIX regex functions (`regcomp()`, `regexec()`, etc.) to do pattern matching on the responses the IMAP server is sending (see `response.c`), and the `regexp.c` file is just implementing some useful functions to compile and free all the regular expressions used.

2. It implements Perl-compatible regular expressions, by using the PCRE library, and it makes this implementation available to the Lua configuration file with the `regex_search()` function, and this implementation can be observed in the `pcre.c` and `regex.lua` files.

Historically, there was no PCRE support in imapfilter, and only standard POSIX regex were used internally (1), but then PCRE support was made available to the users, in order to support local searching in an easy way (2).
