### ISSUE TITLE
generic cron

### ISSUE THREAD

**Issue by kiorky** [lefcha/imapfilter#89]
@lefcha would you be interrested for this to go in your repo:
https://github.com/makinacorpus/imapfilter/blob/master/configs/imapfilter_cron.sh

**Comment by lefcha** [comment]
I'm sorry but generally I am not interested in including a contributors section into the distribution of imapfilter, and that is because usually contributions become out-of-date with time, and I don't want to spend time checking whether they are working and/or fixing them.

Please don't take this personally, as this is just my opinion and policy regarding `contrib` directories as a whole.

Instead, what I would like to do is enable imapfilter's wiki pages, and have links there to all the interesting things people have being doing with it, such as your excellent script.  I hope I will be able to set this up in the near future...
