### ISSUE TITLE
document how to use the NOT logical operator between two mailboxes

### ISSUE THREAD

**Issue by drzraf** [lefcha/imapfilter#97]
I just hit this (probably common) issue yesterday.
I used ```copy_message``` from one mailbox to the other and found that each run of imapfilter would trigger the append message again (although they are not duplicated in the destination mailbox there are still always copied again). But I would like a "sync" where only missing message in the _destination_ are copied from _origin_.

I tried to use the NOT operator, expecting it subsequent runs would only copy missing messages, thus
> results = origin['INBOX']:select_all() - dest['mobile/in']:select_all()                           
> results:copy_messages(dest['mobile/in'])

It does so far it does not work. Should/could it be the case?
(Sorry if it sound more like a mailing-list oriented support request)

**Comment by lefcha** [comment]
Imapfilter is not working the way you expect it, since it is not an IMAP syncing tool (I think there are other utilities that do exactly that).  Imapfilter matches your messages in one or more mailboxes to some filters, and then it can do various things with those messages.

But you could emulate a sync like the one you seem to want.  The logic behind this would be this:

1) Start with an empty destination mailbox, and then select all messages that in your source mailbox.  So:

```lua
results = origin['INBOX']:select_all()
results:copy_messages(dest['mobile/in']
```
2) Then you mark all these same messages in the source mailbox as flagged for special attention:

```lua
results:mark_flagged()
```

3) Now, next time you want to copy only those messages that are new to the source mailbox, you do like this:

```lua
results = origin['INBOX']:is_unflagged()
results:copy_messages(dest['mobile/in'])
```

4) And finally mark those new messages as flagged, so you don't include them next time you sync:

```lua
results:mark_flagged()
```

If those new messages are at some point unseen, you could instead use `is_unseen()` instead of `is_unflagged()` to do the same trick, but you have to make sure that these messages will have been read next time you do a sync; either you mark them manually through your client when you actually read them, or you do it again with imapfilter.

You could also put all the above commands inside a new function:

```lua
function sync(source, dest):
    results = source:is_unflagged()
    results:copy_messages(dest)
    results:mark_flagged()
end
```

And you call it like this:

```lua
sync(origin['INBOX'], dest['mobile/in'])
```

Note, that this method doesn't care for messages that have been deleted from the source mailbox, and thus it is more like a partial sync.  You need to do more advanced stuff and use a bit of Lua, to include this functionality in your config...

**Comment by drzraf** [comment]
thank for the tip.
I was thinking about something like this.
I thought that an UID/ID email header based comparison could maybe
achieved too without messing with flags (I use seen/flag in my MUA).

Happened that I was unsure about offlineimap capability to do such a
remote imap -> remote imap sync (partial/resumed copy)
In the long run I should probably consider a tool best suited for the
tasks (mbsync/isync).

Anyway many thank for the explanations!
