### ISSUE TITLE
Certificate Verification Failed on OS X

### ISSUE THREAD

**Issue by barrymieny** [lefcha/imapfilter#99]
When running imapfilter (2.6.1) I receive the following error: `imapfilter: certificate verification failed; 19`. It was installed with homebrew (and recently upgraded from 2.5.x), but was working without any issues for quite some time before I realised it had stopped working with the latest update. I've searched through the issues but haven't found anything that was able to resolve the error for me.

**Comment by Papafox** [comment]
Error 19 is X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN.  It can indicate that either (a) a certificate signed by an unknown root certificate was encountered; or (b) that a truststore was not found.

The truststore for Imapfilter defaults to settings suitable for Linux and FreeBSD.  Since OSX is based on FreeBSD, I'd expect that Imapfilter would work, but it seems that Apple, as usual, is doing it's own thing.  See https://hynek.me/articles/apple-openssl-verification-surprises/

Is this an urgent issue? I'll look into the problem over the next few days and see if I can work out a fix.  Unfortunately, I don't have access to a Mac for testing, so the fix may take a while.

**Comment by barrymieny** [comment]
Not urgent. Will just manually do everything I set up in the mean time.

**Comment by Papafox** [comment]
There are three possible causes of your problem.  Since two of them don't require access to a Mac to resolve, I'd like to rule them out first.  The possible causes are:

1. The custom OpenSSL build used by OSX is causing the problem.  This requires me the find a Mac I can test on, so I'll address this only after ruling out the next two causes;
2. The email server is using a certificate signed by an unknown issuer.  I can check this by connecting to the server, downloading the cert and examining it.
3. You have an imapfilter config issue, such that it is unable to find the truststore (a file on FreeBSD-based systems).  This is a new feature of v2.6.2

Could you answer the following:
1. What is the domain of the email server you are having issues with?
2. Can you upgrade to Imapfilter v2.6.2 and try again?  New in v2.6.2 is support for CA files, such as those used by FreeBSD.

**Comment by barrymieny** [comment]
1. mail.gandi.net
2. I can only upgrade once its available in homebrew - don't know how long it takes to get updated there.

**Comment by Papafox** [comment]
I've checked mail.gandi.net.  It has the following certificate chain:

    0 s:/OU=Domain Control Validated/OU=Gandi Standard SSL/CN=mail.gandi.net
      i:/C=FR/O=GANDI SAS/CN=Gandi Standard SSL CA
    1 s:/C=FR/O=GANDI SAS/CN=Gandi Standard SSL CA
      i:/C=US/ST=UT/L=Salt Lake City/O=The USERTRUST Network/OU=http://www.usertrust.com/CN=UTN-USERFirst-Hardware
    2 s:/C=US/ST=UT/L=Salt Lake City/O=The USERTRUST Network/OU=http://www.usertrust.com/CN=UTN-USERFirst-Hardware
      i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
    3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
      i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root

So mail.gandi.net has a perfectly valid certificate.  The problem must be caused by Imapfilter not finding the certificates file.

What is the Imapfilter command line you are using?

**Comment by barrymieny** [comment]
I literally just use `imapfilter`, which had worked perfectly for more than a year up until it didn't.

**Comment by Papafox** [comment]
Can you perform two test for me, please?

1. Execute ```imapfilter -V``` to show which version you are running
2. Provide a directory listing of ```/System/Library/Keychains/X509Anchors```. This should list all the trusted root certs available to OpenSSL on a Mac (I hope :-)

**Comment by barrymieny** [comment]
1. `IMAPFilter 2.6.1  Copyright (c) 2001-2015 Eleftherios Chatzimparmpas` - homebrew still doesn't have the latest version available.
2. `/System/Library/Keychains/X509Anchors` is an actual file, not a folder. Keychain Access lists 201 certificates, but offers no way to export this listing.

**Comment by Papafox** [comment]
Ok, since you are running v2.6.1 then you have support for *BSD certificate files.

Try ```imapfilter -t /System/Library/Keychains/X509Anchors``` and see if the certificate error 19 still occurs.

**Comment by barrymieny** [comment]
Yes, it still occurs. The full error message returned is:
```
imapfilter: certificate verification failed; 19
imapfilter: login request to name@domain.com@mail.gandi.net failed
stack traceback:
	[C]: in ?
	[C]: in function 'error'
	...cal/Cellar/imapfilter/2.6.1/share/imapfilter/account.lua:68: in function '_check_result'
	...cal/Cellar/imapfilter/2.6.1/share/imapfilter/account.lua:84: in function '_login_user'
	...cal/Cellar/imapfilter/2.6.1/share/imapfilter/account.lua:46: in function 'IMAP'
	/Users/barry/.imapfilter/config.lua:15: in main chunk
```

**Comment by Papafox** [comment]
I'll have to get access to a Mac and do some debugging.  It may take a while, so bear with me.

**Comment by tlevine** [comment]
I just got a Mac and am now having the same issue. I'm using the same configuration file on Debian and on Mac, and it works on Debian but not on Mac.
```
$ imapfilter -V
IMAPFilter 2.6.1  Copyright (c) 2001-2015 Eleftherios Chatzimparmpas
```

**Comment by soli** [comment]
Same issue, same version (2.6.1 from homebrew) [on OSX 10.8.5]

**Comment by gdolle** [comment]
I had the same issue with FreeBSD, I had to use this path 
```imapfilter -t /usr/local/etc/ssl/certs.pem```
to make it works.
It might me something similar on OSX ? (Check maybe with `/usr/local/etc/openssl/certs.pem` ?)

**Comment by wmealing** [comment]
imapfilter -t /usr/local/etc/openssl/cert.pem

Worked for me.

**Comment by hcampan** [comment]
Thanks,

imapfilter -t /usr/local/etc/openssl/cert.pem

Worked for me on :
* IMAPFilter 2.6.5 (installed & upgraded with Homebrew)
* MAC OSX 10.11.3, 10.6.8

Hubert

**Comment by FabriceSalvaire** [comment]
I got this error on centos 7.4 after yum updated to imapfilter-2.6.10-2.el7

I used `-t /etc/pki/tls/cert.pem` to recover

**Comment by lefcha** [comment]
Seems each OS uses a different location for the `cert.pem` or the certs dir, so it's necessary to override the default location with the `-t` option.

**Comment by uinput** [comment]
@lefcha Would it be possible to add `/etc/pki/tls/cert.pem` to the list of default locations to look for a file? RPM-based distribution users would really appreciate it.

**Comment by krischik** [comment]
Same here:

```
imapfilter: certificate verification failed; self signed certificate in certificate chain
imapfilter: login request to XXXX@me.com@imap.mail.me.com failed
```

It worked fine with 2.5…

**Comment by krischik** [comment]
And back again to the same problem. It seems out of the blue imapfilter refuses all certificates.

Could we have a few more debugging information to better see where the problem is?

**Comment by lefcha** [comment]
If you're using 2.6.13/14 then it's probably the hostname validation support, together with an invalid local CA certs truststore: https://github.com/lefcha/imapfilter/issues/201
